### ISSUE TITLE
[bug] TypeError: this.awsPackagePlugin.validateStatements is not a function

### ISSUE THREAD

**Issue by AshKapow** [glasswall-sre/dead-letter-watcher#32]
The CD pipeline is failing on "Serverless Deploy to AWS" with the following error:

/home/runner/work/dead-letter-watcher/dead-letter-watcher/deadletter_listener
Serverless: Generating requirements.txt from Pipfile...
Serverless: Parsed requirements.txt from Pipfile in /home/runner/work/dead-letter-watcher/dead-letter-watcher/deadletter_listener/.serverless/requirements.txt...
Serverless: Installing requirements from /home/runner/.cache/serverless-python-requirements/3aa4c6b1cb428516985628fbbb62e5f0556927c687b709156580ccc67a7d8666_slspyc/requirements.txt ...
Serverless: Using download cache directory /home/runner/.cache/serverless-python-requirements/downloadCacheslspyc
Serverless: Running ...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Injecting required Python packages to package...
 
  Type Error ---------------------------------------------
 
  TypeError: this.awsPackagePlugin.validateStatements is not a function
      at ServerlessIamPerFunctionPlugin.validateStatements (/home/runner/work/dead-letter-watcher/dead-letter-watcher/deadletter_listener/node_modules/serverless-iam-roles-per-function/src/lib/index.ts:62:27)
      at ServerlessIamPerFunctionPlugin.createRoleForFunction (/home/runner/work/dead-letter-watcher/dead-letter-watcher/deadletter_listener/node_modules/serverless-iam-roles-per-function/src/lib/index.ts:209:10)
      at ServerlessIamPerFunctionPlugin.createRolesPerFunction (/home/runner/work/dead-letter-watcher/dead-letter-watcher/deadletter_listener/node_modules/serverless-iam-roles-per-function/src/lib/index.ts:306:12)
      at /opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/serverless/lib/classes/PluginManager.js:510:55
      at tryCatcher (/opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (/opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.18.4
     Framework Version:         2.5.0
     Plugin Version:            4.0.4
     SDK Version:               2.3.2
     Components Version:        3.2.1
 
Error: Process completed with exit code 1.

**Comment by AshKapow** [comment]
See the following GitHub issues for more information:
https://github.com/serverless/serverless/issues/8358
https://github.com/functionalone/serverless-iam-roles-per-function/issues/52

For now I am hardcoding the Serverless version as per the workaround

**Comment by mukulgupta2138** [comment]
Discussed with @AshKapow , our CI/CD pipelines are good shape and working as expected. This issue no longer exists.
